// SPDX-License-Identifier: FSL-1.1-MIT

import { Injectable } from '@nestjs/common';
import { HttpAdapterHost } from '@nestjs/core';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { HttpMethod } from '@/modules/auth/mcp/routes/entities/mcp-tool-arguments.entity';

// Where `SwaggerModule.setup('api', ...)` in `app.provider.ts` serves the document.
const OPENAPI_DOCUMENT_PATH = '/api-json';
const SCHEMA_REF_PREFIX = '#/components/schemas/';
const HTTP_METHODS: ReadonlyArray<HttpMethod> = [
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
];

const OpenApiOperationSchema = z.object({
  operationId: z.string().optional(),
  summary: z.string().optional(),
  description: z.string().optional(),
  tags: z.array(z.string()).optional(),
  deprecated: z.boolean().optional(),
  parameters: z.array(z.unknown()).optional(),
  requestBody: z.unknown().optional(),
  responses: z.record(z.string(), z.unknown()).optional(),
});

const OpenApiDocumentSchema = z.object({
  paths: z.record(z.string(), z.record(z.string(), z.unknown())),
  components: z
    .object({ schemas: z.record(z.string(), z.unknown()).optional() })
    .optional(),
});

type OpenApiOperation = z.infer<typeof OpenApiOperationSchema>;

type CatalogEntry = {
  method: HttpMethod;
  path: string;
  pattern: RegExp;
  operation: OpenApiOperation;
};

type Catalog = {
  entries: Array<CatalogEntry>;
  schemas: Record<string, unknown>;
};

export type EndpointSummary = {
  method: HttpMethod;
  path: string;
  summary?: string;
  tags?: Array<string>;
  deprecated?: boolean;
};

/**
 * The gateway's own OpenAPI document, as the catalogue the MCP tools search,
 * describe and check calls against. Generated by `@nestjs/swagger` from the
 * controllers, so it lists exactly the routes the app serves.
 */
@Injectable()
export class OpenApiCatalogService {
  private catalog?: Promise<Catalog>;

  constructor(private readonly httpAdapterHost: HttpAdapterHost) {}

  /**
   * Endpoints whose method, path, summary, tags or operation id contain every
   * word of {@link query}, case-insensitively.
   */
  async search(query: string | undefined): Promise<Array<EndpointSummary>> {
    const { entries } = await this.getCatalog();
    const words = (query ?? '').toLowerCase().split(/\s+/).filter(Boolean);

    return entries
      .filter((entry) => {
        const haystack = [
          entry.method,
          entry.path,
          entry.operation.summary,
          entry.operation.operationId,
          ...(entry.operation.tags ?? []),
        ]
          .join(' ')
          .toLowerCase();
        return words.every((word) => haystack.includes(word));
      })
      .map(({ method, path, operation }) => ({
        method,
        path,
        summary: operation.summary,
        tags: operation.tags,
        deprecated: operation.deprecated,
      }));
  }

  /**
   * The full definition of one endpoint, with schema references inlined.
   *
   * @param path - The path template, e.g. `/v1/spaces/{id}`.
   */
  async describe(
    method: HttpMethod,
    path: string,
  ): Promise<Record<string, unknown> | undefined> {
    const { entries, schemas } = await this.getCatalog();
    const entry = entries.find((e) => e.method === method && e.path === path);
    if (!entry) {
      return undefined;
    }

    const successResponses = Object.fromEntries(
      Object.entries(entry.operation.responses ?? {}).filter(([status]) =>
        status.startsWith('2'),
      ),
    );

    return {
      method,
      path,
      summary: entry.operation.summary,
      description: entry.operation.description,
      tags: entry.operation.tags,
      deprecated: entry.operation.deprecated,
      parameters: resolveRefs(entry.operation.parameters, schemas),
      requestBody: resolveRefs(entry.operation.requestBody, schemas),
      responses: resolveRefs(successResponses, schemas),
    };
  }

  /**
   * The documented endpoint a concrete request path is served by, if any.
   *
   * @param path - A concrete path, e.g. `/v1/spaces/12`.
   */
  async findEndpoint(
    method: HttpMethod,
    path: string,
  ): Promise<EndpointSummary | undefined> {
    const { entries } = await this.getCatalog();
    const entry = entries.find(
      (e) => e.method === method && e.pattern.test(path),
    );
    return entry && { method: entry.method, path: entry.path };
  }

  private getCatalog(): Promise<Catalog> {
    this.catalog ??= this.loadCatalog().catch((error: unknown) => {
      // Retry on the next call rather than caching the failure.
      this.catalog = undefined;
      throw error;
    });
    return this.catalog;
  }

  private async loadCatalog(): Promise<Catalog> {
    const response = await this.httpAdapterHost.httpAdapter
      .getInstance<FastifyInstance>()
      .inject({ method: 'GET', url: OPENAPI_DOCUMENT_PATH });
    const document = OpenApiDocumentSchema.parse(response.json());

    const entries = Object.entries(document.paths).flatMap(([path, item]) =>
      HTTP_METHODS.flatMap((method) => {
        const operation = item[method.toLowerCase()];
        if (operation === undefined) {
          return [];
        }
        return [
          {
            method,
            path,
            pattern: toPathPattern(path),
            operation: OpenApiOperationSchema.parse(operation),
          },
        ];
      }),
    );

    return { entries, schemas: document.components?.schemas ?? {} };
  }
}

/**
 * Matches a concrete path against an OpenAPI path template: each `{param}`
 * stands for exactly one segment. A trailing slash is tolerated, as the router
 * ignores it.
 */
function toPathPattern(template: string): RegExp {
  const source = template
    .split(/(\{[^}]+\})/)
    .map((part) =>
      part.startsWith('{')
        ? '[^/]+'
        : part.replace(/[.*+?^$()|[\]\\]/g, '\\$&'),
    )
    .join('');
  return new RegExp(`^${source}/?$`);
}

/**
 * Inlines `#/components/schemas/*` references. A schema that refers to itself,
 * directly or through others, keeps its innermost reference unresolved.
 */
function resolveRefs(
  value: unknown,
  schemas: Record<string, unknown>,
  resolving: ReadonlySet<string> = new Set(),
): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => resolveRefs(item, schemas, resolving));
  }
  if (typeof value !== 'object' || value === null) {
    return value;
  }

  const ref = (value as { $ref?: unknown }).$ref;
  if (typeof ref === 'string' && ref.startsWith(SCHEMA_REF_PREFIX)) {
    const name = ref.slice(SCHEMA_REF_PREFIX.length);
    if (resolving.has(name) || !(name in schemas)) {
      return value;
    }
    return resolveRefs(schemas[name], schemas, new Set([...resolving, name]));
  }

  return Object.fromEntries(
    Object.entries(value).map(([key, item]) => [
      key,
      resolveRefs(item, schemas, resolving),
    ]),
  );
}
