version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      nest-js-core:
        patterns:
          - '@nestjs/common'
          - '@nestjs/core'
          - '@nestjs/platform-express'
          - '@nestjs/testing'
      aws-sdk:
        patterns:
          - '@aws-sdk/*'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
