# SPDX-License-Identifier: FSL-1.1-MIT

services:
  redis:
    image: redis/redis-stack:7.2.0-v10
    ports:
      - ${REDIS_PORT-6379}:${REDIS_PORT-6379}
      - 8001:8001

  db:
    image: postgres:14.8-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db_config/test/server.crt:/var/lib/postgresql/server.crt:ro
      - ./db_config/test/server.key:/var/lib/postgresql/server.key:ro
      - ./db_config/test/pg_hba.conf:/etc/pg_hba.conf
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-safe-client-gateway}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c hba_file=/etc/pg_hba.conf

  db-test:
    image: postgres:14.8-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB:-test-db}
      POSTGRES_USER: ${POSTGRES_TEST_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_TEST_PORT:-5433}:5432"
    volumes:
      - ./db_config/test/server.crt:/var/lib/postgresql/server.crt:ro
      - ./db_config/test/server.key:/var/lib/postgresql/server.key:ro
      - ./db_config/test/pg_hba.conf:/etc/pg_hba.conf
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c hba_file=/etc/pg_hba.conf

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 15s

  web:
    build: .
    tty: true
    environment:
      - REDIS_HOST=redis
      - TX_SERVICE_API_KEY
      - ALERTS_PROVIDER_ACCOUNT
      - ALERTS_PROVIDER_API_BASE_URI
      - ALERTS_PROVIDER_API_KEY
      - ALERTS_PROVIDER_PROJECT
      - ALERTS_PROVIDER_SIGNING_KEY
      - AUTH_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_KMS_ENCRYPTION_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - BLOCKLIST_ENCRYPTED_DATA
      - BLOCKLIST_SECRET_KEY
      - BLOCKLIST_SECRET_SALT
      - BRIDGE_API_KEY
      - CGW_ENV
      - CSV_AWS_ACCESS_KEY_ID
      - CSV_AWS_SECRET_ACCESS_KEY
      - EMAIL_API_APPLICATION_CODE
      - EMAIL_API_FROM_EMAIL
      - EMAIL_API_KEY
      - FF_AUTH
      - FF_CONFIG_HOOKS_DEBUG_LOGS
      - FF_COUNTERFACTUAL_BALANCES
      - FF_DEBUG_LOGS
      - FF_EMAIL
      - FF_ETH_SIGN
      - FF_FILTER_VALUE_PARSING
      - FF_HASH_VERIFICATION_API
      - FF_HASH_VERIFICATION_PROPOSAL
      - FF_HOOK_HTTP_POST_EVENT
      - FF_IMPROVED_ADDRESS_POISONING
      - FF_LIFITRANSACTIONS_MAPPING
      - FF_MESSAGE_VERIFICATION
      - FF_SIGNATURE_VERIFICATION_API
      - FF_SIGNATURE_VERIFICATION_PROPOSAL
      - FF_TRUSTED_DELEGATE_CALL
      - FF_TRUSTED_FOR_DELEGATE_CALL_CONTRACTS_LIST
      - FF_USERS
      - FF_VAULT_TRANSACTIONS_MAPPING
      - FF_ZERION_BALANCES_CHAIN_IDS
      - FF_ZERION_ENABLED
      - FF_ZERION_POSITIONS_DISABLED
      - FINGERPRINT_ENCRYPTION_KEY
      - INFURA_API_KEY
      - JWT_ISSUER
      - JWT_SECRET
      - POSTGRES_SSL_ENABLED
      - POSTGRES_SSL_REJECT_UNAUTHORIZED
      - PUSH_NOTIFICATIONS_API_PROJECT
      - PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_CLIENT_EMAIL
      - RELAY_DAILY_LIMIT_CHAIN_IDS
      - RELAY_NO_FEE_CAMPAIGN_MAINNET_SAFE_TOKEN_ADDRESS
      - RELAY_PROVIDER_API_KEY
      - STAKING_API_KEY
      - STAKING_TESTNET_API_KEY
      - ALLOW_CORS
      - SAFE_CONFIG_BASE_URI
      - RELAY_FEE_CHAIN_IDS
      - RELAY_SIMULATION_CHAIN_IDS
      - FEE_SERVICE_BASE_URI
      - AUTH_POST_LOGIN_REDIRECT_URI
      - RELAY_SAFE_PAYS_REFUND_RECEIVER
      - RELAY_NO_FEE_CAMPAIGN_MAINNET_RELAY_RULES
      - RELAY_NO_FEE_CAMPAIGN_SEPOLIA_RELAY_RULES
      - FINGERPRINT_ENCRYPTION_KEY
      - PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_PRIVATE_KEY
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - redis
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_ADMIN_USER:-admin@test.dev}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_ADMIN_PASS:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  nginx:
    image: nginx:1.25-alpine
    ports:
      - ${NGINX_HOST_PORT:-8080}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/
      APPLICATION_PORT: ${APPLICATION_PORT-3000}
    depends_on:
      - web

volumes:
  pgadmin-data:
