export enum EventType {
  NEW_CONFIRMATION = 'NEW_CONFIRMATION',
  EXECUTED_MULTISIG_TRANSACTION = 'EXECUTED_MULTISIG_TRANSACTION',
  PENDING_MULTISIG_TRANSACTION = 'PENDING_MULTISIG_TRANSACTION',
  INCOMING_TOKEN = 'INCOMING_TOKEN',
  INCOMING_ETHER = 'INCOMING_ETHER',
  MODULE_TRANSACTION = 'MODULE_TRANSACTION',
  OUTGOING_TOKEN = 'OUTGOING_TOKEN',
  OUTGOING_ETHER = 'OUTGOING_ETHER',
  MESSAGE_CREATED = 'MESSAGE_CREATED',
  MESSAGE_CONFIRMATION = 'MESSAGE_CONFIRMATION',
}

export type EventPayload<T extends EventType> = {
  address: string;
  chainId: string;
  type: T;
};
