export enum NotificationType {
  CONFIRMATION_REQUEST = 'CONFIRMATION_REQUEST',
  DELETED_MULTISIG_TRANSACTION = 'DELETED_MULTISIG_TRANSACTION',
  EXECUTED_MULTISIG_TRANSACTION = 'EXECUTED_MULTISIG_TRANSACTION',
  INCOMING_ETHER = 'INCOMING_ETHER',
  INCOMING_TOKEN = 'INCOMING_TOKEN',
  MESSAGE_CONFIRMATION_REQUEST = 'MESSAGE_CONFIRMATION_REQUEST',
  MODULE_TRANSACTION = 'MODULE_TRANSACTION',
}
