import { Schema } from 'ajv';
import { confirmationSchema } from './multisig-transaction.schema';
import { dataDecodedSchema } from '../../../data-decoder/entities/schemas/data-decoded.schema';

export const multisigTransactionTypeSchema: Schema = {
  type: 'object',
  properties: {
    txType: { type: 'string', const: 'MULTISIG_TRANSACTION' },
    safe: { type: 'string' },
    to: { type: 'string' },
    value: { type: 'string', nullable: true },
    data: { type: 'string', nullable: true },
    dataDecoded: dataDecodedSchema,
    operation: { type: 'number', enum: [0, 1] },
    gasToken: { type: 'string', nullable: true },
    safeTxGas: { type: 'number', nullable: true },
    baseGas: { type: 'number', nullable: true },
    gasPrice: { type: 'string', nullable: true },
    refundReceiver: { type: 'string', nullable: true },
    nonce: { type: 'number' },
    executionDate: { type: 'string', nullable: true },
    submissionDate: { type: 'string', nullable: true },
    modified: { type: 'string', nullable: true },
    blockNumber: { type: 'number', nullable: true },
    transactionHash: { type: 'string', nullable: true },
    safeTxHash: { type: 'string' },
    executor: { type: 'string', nullable: true },
    isExecuted: { type: 'boolean' },
    isSuccessful: { type: 'boolean', nullable: true },
    ethGasPrice: { type: 'string', nullable: true },
    gasUsed: { type: 'number', nullable: true },
    fee: { type: 'string', nullable: true },
    origin: { type: 'string', nullable: true },
    confirmationsRequired: { type: 'number', nullable: true },
    confirmations: {
      type: 'array',
      nullable: true,
      items: confirmationSchema,
    },
    signatures: { type: 'string', nullable: true },
  },
  required: [
    'txType',
    'safe',
    'to',
    'operation',
    'nonce',
    'safeTxHash',
    'isExecuted',
  ],
};
