// SPDX-License-Identifier: FSL-1.1-MIT
/**
 * Generates a KMS-wrapped data key for field-level encryption (the app-wide
 * blind-index key).
 *
 * Envelope encryption: KMS protects the data key; the app performs local
 * HMAC computation with it. This script produces the *encrypted* data key
 * (safe to store in config). The plaintext key material is generated by KMS,
 * used by KMS only, and never printed or persisted here.
 *
 * Usage:
 *   AWS_KMS_ENCRYPTION_KEY_ID=<arn-or-id> AWS_REGION=<region> \
 *     ts-node scripts/generate-field-encryption-data-key.ts [--key-id=<id>]
 *
 * Outputs the values to set:
 *   SPACES_FIELD_ENCRYPTION_INDEX_KEY_ID
 *   SPACES_FIELD_ENCRYPTION_DATA_KEYS   (JSON map of keyId -> base64 wrapped key)
 *
 * Keep old entries in the SPACES_FIELD_ENCRYPTION_DATA_KEYS map when adding a
 * key so previously-computed blind indexes stay verifiable.
 */
import { GenerateDataKeyCommand, KMSClient } from '@aws-sdk/client-kms';
import { fromTokenFile } from '@aws-sdk/credential-provider-web-identity';

function getKeyIdArg(): string {
  const arg = process.argv.find((a) => a.startsWith('--key-id='));
  const keyId = arg ? arg.slice('--key-id='.length) : '1';
  if (!keyId || keyId.includes(':')) {
    throw new Error('--key-id must be non-empty and must not contain ":"');
  }
  return keyId;
}

function resolveCredentials():
  | ReturnType<typeof fromTokenFile>
  | { accessKeyId: string; secretAccessKey: string }
  | undefined {
  // Set in EKS via IRSA; takes precedence over static credentials.
  if (process.env.AWS_WEB_IDENTITY_TOKEN_FILE) {
    return fromTokenFile();
  }
  if (process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY) {
    return {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    };
  }
  // Fall back to the default AWS credential provider chain.
  return undefined;
}

async function main(): Promise<void> {
  const kmsKeyId = process.env.AWS_KMS_ENCRYPTION_KEY_ID;
  if (!kmsKeyId) {
    throw new Error('AWS_KMS_ENCRYPTION_KEY_ID is required');
  }
  const region = process.env.AWS_REGION;
  if (!region) {
    throw new Error('AWS_REGION is required');
  }
  const keyId = getKeyIdArg();

  const client = new KMSClient({ region, credentials: resolveCredentials() });

  const response = await client.send(
    new GenerateDataKeyCommand({ KeyId: kmsKeyId, KeySpec: 'AES_256' }),
  );

  if (!response.CiphertextBlob) {
    throw new Error('KMS did not return an encrypted data key');
  }

  // Zero out the plaintext key material as soon as possible; we must never
  // print or persist it.
  if (response.Plaintext) {
    Buffer.from(response.Plaintext).fill(0);
  }

  const encrypted = Buffer.from(response.CiphertextBlob).toString('base64');

  console.info(
    [
      '',
      'Generated a new KMS-wrapped data key. Set the following in your environment:',
      '',
      `SPACES_FIELD_ENCRYPTION_INDEX_KEY_ID=${keyId}`,
      `SPACES_FIELD_ENCRYPTION_DATA_KEYS=${JSON.stringify({ [keyId]: encrypted })}`,
      '',
      'When adding a key, merge this entry into the existing SPACES_FIELD_ENCRYPTION_DATA_KEYS map',
      'and keep prior entries so previously-computed blind indexes stay verifiable.',
      '',
    ].join('\n'),
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
