export enum TransactionEventType {
  DELETED_DELEGATE = 'DELETED_DELEGATE',
  DELETED_MULTISIG_TRANSACTION = 'DELETED_MULTISIG_TRANSACTION',
  EXECUTED_MULTISIG_TRANSACTION = 'EXECUTED_MULTISIG_TRANSACTION',
  INCOMING_ETHER = 'INCOMING_ETHER',
  INCOMING_TOKEN = 'INCOMING_TOKEN',
  MESSAGE_CONFIRMATION = 'MESSAGE_CONFIRMATION',
  MESSAGE_CREATED = 'MESSAGE_CREATED',
  MODULE_TRANSACTION = 'MODULE_TRANSACTION',
  NEW_CONFIRMATION = 'NEW_CONFIRMATION',
  NEW_DELEGATE = 'NEW_DELEGATE',
  OUTGOING_ETHER = 'OUTGOING_ETHER',
  OUTGOING_TOKEN = 'OUTGOING_TOKEN',
  PENDING_MULTISIG_TRANSACTION = 'PENDING_MULTISIG_TRANSACTION',
  REORG_DETECTED = 'REORG_DETECTED',
  SAFE_CREATED = 'SAFE_CREATED',
  UPDATED_DELEGATE = 'UPDATED_DELEGATE',
}

export enum ConfigEventType {
  CHAIN_UPDATE = 'CHAIN_UPDATE',
  SAFE_APPS_UPDATE = 'SAFE_APPS_UPDATE',
}
